### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by mechanicpanic** [AMArostegui/CoreNLPClient.Net#3]
Hi! We're using your project for our tool: https://github.com/yakovypg/Chat-Corpora-Annotator 
Since there's no license listed, we've assumed it was okay for us to use it. However, we'd like to make sure it's okay. Do you think it could be possible for you to add a license to your project, so we know exactly how to proceed? 

Thanks in advance!

**Comment by AMArostegui** [comment]
Added. It's MIT
